### ISSUE TITLE
Fails on macOS 12.3+

### ISSUE THREAD

**Issue by biocross** [sindresorhus/create-dmg#69] opened 2022-04-16 11:29 UTC
Fails on the latest macOS Monterey with the error:

```
ℹ Minimum runtime 10.13 detected, using ULFO format
✖ Building the DMG failed. Error: Command failed: bless --folder /Volumes/AppName --openfolder /Volumes/AppName
bless: The 'openfolder' is not supported on Apple Silicon devices.
```

I ran the command with no extra options, like `create-dmg AppName.app`.

Likely related issue: https://github.com/create-dmg/create-dmg/issues/127

**Comment by sindresorhus** [comment] 2022-04-18 16:20
Duplicate of #68

**Closed by sindresorhus** 2022-04-18 16:20 UTC
